#!/bin/sh

if [ $1 = 'remove' ] && [ -L /usr/local/bin/cellery ]
then
  sudo rm /usr/local/bin/cellery
fi

if [ $1 = 'purge' ]  && [ -L /usr/local/bin/cellery ]
then
	echo "Remove configuration files."
	sudo rm /usr/local/bin/cellery
fi
sudo rm -rf /usr/share/cellery/

BRE_LIB_PATH="/usr/lib/ballerina/ballerina-0.990.3/bre/lib"
if [ -d $BRE_LIB_PATH ]
then
sudo rm -f ${BRE_LIB_PATH}/cellery-0.2.0-SNAPSHOT.jar
fi


