#!/bin/bash

if [ "$1" = configure ]; then
    echo "Cellery is configured successfully."
fi

if [ "$1" = abort-upgrade ]; then
    echo "Aborting the installation without upgrading."
    exit 0
fi

#echo "Post installation process started"
PRODUCT_HOME=/usr/share/cellery
CELLERY_VERSION=__CELLERY_VERSION__
SUPPORTED_B7A_VERSION="1.0.1"
BALLERINA_RUNTIME="ballerina-${SUPPORTED_B7A_VERSION}"
chmod -R 0755 ${PRODUCT_HOME}

B7A_BIN_PATH=$(which ballerina)
if [ -L "${B7A_BIN_PATH}" ]; then
    B7A_BIN_PATH=$(readlink $B7A_BIN_PATH)
fi

B7A_VERSION=$($B7A_BIN_PATH -v)
if [ ! -f ${B7A_BIN_PATH} ]; then
    B7A_BIN_PATH="/usr/lib/ballerina/${BALLERINA_RUNTIME}/bin"
    echo "Failed to find the ballerina home directory, falling back to the default installation path."
    echo $B7A_BIN_PATH
fi

if [[ "${B7A_VERSION}" =~ "${SUPPORTED_B7A_VERSION}" ]]; then
    echo "B7A version $B7A_VERSION"
    echo "Correct B7A version installed."
    echo "User needs to copy /usr/share/cellery/b7a-libs/ballerina-${SUPPORTED_B7A_VERSION}/balo_cache/celleryio/cellery/${CELLERY_VERSION}/cellery-2019r3-java8-0.5.0.balo to ~/.ballerina/balo_cache/celleryio/cellery/0.5.0"
else
#Pull docker based Ballerina cli.
    echo "Ballerina ${SUPPORTED_B7A_VERSION} is not installed"
    echo "Installing docker based Cellery CLI."
    docker_status=$(docker info 2>&1 1>/dev/null)
    if [[ $? -eq 0 ]]; then
        echo "Pulling the docker based Cellery CLI image : wso2cellery/ballerina-runtime:${CELLERY_VERSION}"
        docker pull wso2cellery/ballerina-runtime:${CELLERY_VERSION}
    else
        echo "Local Docker service is not ready. Installer can not pull the docker based Cellery CLI image."
    fi
fi
echo "Post installation process finished"
