#!/bin/bash

CELLERY_VERSION=__CELLERY_VERSION__
CELLERY_VERSION_NUM="${CELLERY_VERSION/-SNAPSHOT/}"
if [ $1 = 'remove' ] && [ -L /usr/local/bin/cellery ]
then
  sudo rm /usr/local/bin/cellery
fi

if [ $1 = 'purge' ]  && [ -L /usr/local/bin/cellery ]
then
	echo "Remove configuration files."
	sudo rm /usr/local/bin/cellery
fi
# Remove Cellery installation.
sudo rm -rf /usr/share/cellery/

echo "Remove ~/.ballerina/balo_cache/celleryio/cellery/0.5.0/cellery-2019r3-java8-${CELLERY_VERSION_NUM}.balo to
      complete the Cellery uninstallation."

