#!/bin/bash

if [ "$1" = configure ]; then
    echo "Cellery is configured successfully."
fi

if [ "$1" = abort-upgrade ]; then
    echo "Aborting the installation without upgrading."
    exit 0
fi

#echo "Post installation process started"
PRODUCT_HOME=/usr/share/cellery
BALLERINA_RUNTIME="ballerina-0.991.0"
CELLERY_VERSION=__CELLERY_VERSION__
SUPPORTED_B7A_VERSION="0.991.0"
chmod -R 0755 ${PRODUCT_HOME}
chmod 0644 ${PRODUCT_HOME}/repo/celleryio/cellery/*/cellery.zip

B7A_BIN_PATH=$(which ballerina)
if [ -L "${B7A_BIN_PATH}" ]; then
    B7A_BIN_PATH=$(readlink $B7A_BIN_PATH)
fi

B7A_VERSION=$($B7A_BIN_PATH -v)
if [ ! -f ${B7A_BIN_PATH} ]; then
    B7A_BIN_PATH="/usr/lib/ballerina/ballerina-0.991.0/bin"
    echo "Failed to find the ballerina home directory, falling back to the default installation path."
    echo $B7A_BIN_PATH
fi

if [[ "${B7A_VERSION}" =~ "${SUPPORTED_B7A_VERSION}" ]]; then
    echo "B7A version $B7A_VERSION"
    echo "Correct B7A version installed."

    BIN_FOLDER="/bin/ballerina"
    BALLERINA_HOME="${B7A_BIN_PATH/$BIN_FOLDER/}"
    CELLERY_JAR="${BALLERINA_HOME}/bre/lib/cellery-${CELLERY_VERSION}.jar"

    if [[ -f "${CELLERY_JAR}" ]]; then
        rm -f ${BALLERINA_HOME}/bre/lib/cellery-${CELLERY_VERSION}.jar
        echo "Removed the stale jar ${BALLERINA_HOME}/bre/lib/cellery-${CELLERY_VERSION}.jar"
    fi
    cp /usr/share/cellery/bre-libs/ballerina-0.991.0/bre/lib/cellery-${CELLERY_VERSION}.jar ${BALLERINA_HOME}/bre/lib/
else
#Pull docker based Ballerina cli.
    echo "Ballerina 0.991.0 is not installed"
    echo "Installing docker based Cellery CLI."
    docker_status=$(docker info 2>&1 1>/dev/null)
    if [[ $? -eq 0 ]]; then
        echo "Pulling the docker based Cellery CLI image : wso2cellery/ballerina-runtime:${CELLERY_VERSION}"
        docker pull wso2cellery/ballerina-runtime:${CELLERY_VERSION}
    else
        echo "Local Docker service is not ready. Installer can not pull the docker based Cellery CLI image."
    fi
fi
echo "Post installation process finished"
