#!/bin/bash
# ----------------------------------------------------------------------------------
# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# ----------------------------------------------------------------------------------
#

#echo "Post installation process started"
PRODUCT_HOME=/Library/Cellery
SUPPORTED_B7A_VERSION=__SUPPORTED_B7A_VERSION__
BALLERINA_RUNTIME="ballerina-${SUPPORTED_B7A_VERSION}"
CELLERY_VERSION=__CELLERY_VERSION__

# Change permissions in home directory
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

# Add cellery shortcut to /usr/local/bin
rm -f /usr/local/bin/cellery
ln -s ${PRODUCT_HOME}/cellery /usr/local/bin/cellery

B7A_HOME="/Library/Ballerina/${BALLERINA_RUNTIME}"
if [ ! -d ${B7A_HOME} ]
then
#Pull docker based Ballerina cli.
    echo "Ballerina ${SUPPORTED_B7A_VERSION} is not installed"
    echo "Installing docker based Cellery CLI."
    docker_status=$(/usr/local/bin/docker info 2>&1 1>/dev/null)
    if [[ $? -eq 0 ]]; then
        echo "Pulling the docker based Cellery CLI image : wso2cellery/ballerina-runtime:${CELLERY_VERSION}"
        /usr/local/bin/docker pull wso2cellery/ballerina-runtime:${CELLERY_VERSION}
    else
        echo "Local Docker service is not ready. Installer can not pull the docker based Cellery CLI image."
    fi
fi
echo "Post installation process finished"
