#!/bin/bash
# ----------------------------------------------------------------------------------
# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# ----------------------------------------------------------------------------------
#

#echo "Post installation process started"
PRODUCT_HOME=/Library/Cellery
BALLERINA_RUNTIME="ballerina-0.990.3"
CELLERY_VERSION="0.2.1"

# Change permissions in home directory
cd ${PRODUCT_HOME}
chmod -R 755 .
chmod 0644 repo/celleryio/cellery/*/cellery.zip
[ -d /usr/local/bin ] || mkdir /usr/local/bin

# Add cellery shortcut to /usr/local/bin
rm -f /usr/local/bin/cellery
ln -s ${PRODUCT_HOME}/cellery /usr/local/bin/cellery
#echo "Post installation process finished"

BRE_LIB_PATH="/Library/Ballerina/ballerina-0.990.3/bre/lib/"
if [ -d $BRE_LIB_PATH ]
then
    cp /Library/Cellery/bre-libs/${BALLERINA_RUNTIME}/bre/lib/*.jar ${BRE_LIB_PATH}
else
#Pull docker based Ballerina cli.
    echo "Ballerina 0.990.3 is not installed"
    echo "Installing docker based Cellery CLI."
    docker_status=$(docker info 2>&1 1>/dev/null)
    if [ $? -eq 0 ]; then
        echo "Pulling the docker based Cellery CLI image : wso2cellery/ballerina-runtime:${CELLERY_VERSION}"
        docker pull wso2cellery/ballerina-runtime:${CELLERY_VERSION}
    else
        echo "Local Docker service is not ready. Installer can not pull the docker based Cellery CLI image."
    fi
fi
echo "Post installation process finished"
