#!/bin/bash
# ----------------------------------------------------------------------------------
# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# ----------------------------------------------------------------------------------
#

#echo "Post installation process started"
PRODUCT_HOME=/Library/Cellery
BALLERINA_RUNTIME="ballerina-0.990.3"

# Change permissions in home directory
cd ${PRODUCT_HOME}
chmod -R 755 .
chmod 0644 repo/celleryio/cellery/*/cellery.zip
[ -d /usr/local/bin ] || mkdir /usr/local/bin

# create a symlink so that executable path can be used without version
SYMLINK_DIR=${PRODUCT_HOME}/runtime/executable
mkdir -p ${SYMLINK_DIR}
ln -sf ${PRODUCT_HOME}/runtime/${BALLERINA_RUNTIME}/bin/ballerina ${SYMLINK_DIR}/ballerina

# Add cellery shortcut to /usr/local/bin
rm -f /usr/local/bin/cellery
ln -s ${PRODUCT_HOME}/cellery /usr/local/bin/cellery
#echo "Post installation process finished"
